toon:
  pdl:
    fetch-url: ${TOON_PDL_FETCH_URL:http://feeds.feedburner.com/PoorlyDrawnLines}
    pullDelayMs: ${TOON_PDL_PULL_DELAY_MS:75}
  xkcd:
    fetch-url: ${TOON_XKCD_FETCH_URL:https://xkcd.com/info.0.json}
    fetch-url-by-id: ${TOON_XKCD_FETCH_URL_BY_ID:https://xkcd.com/~ID~/info.0.json}
    web-url: ${TOON_XKCD_WEB_URL:https://xkcd.com/~ID~/}
    pullDelayMs: ${TOON_XKCD_PULL_DELAY_MS:75}
logging:
  level:
    root: INFO
    com.mrazjava.toonfeed: INFO
    org.springframework: WARN
