toon:
  pdl:
    fetch-limit: ${TOON_PDL_FETCH_LIMIT:10}
    fetch-url: ${TOON_PDL_FETCH_URL:http://feeds.feedburner.com/PoorlyDrawnLines}
    # delay when pulling toons initially up to fetch-limit
    pull-delay-ms: ${TOON_PDL_PULL_DELAY_MS:75}
    # once fetch-limit is reached, pull is issued with this delay
    pull-delay-min: ${TOON_PDL_PULL_DELAY_MIN:60}
  xkcd:
    fetch-limit: ${TOON_XKCD_FETCH_LIMIT:10}
    fetch-url: ${TOON_XKCD_FETCH_URL:https://xkcd.com/info.0.json}
    fetch-url-by-id: ${TOON_XKCD_FETCH_URL_BY_ID:https://xkcd.com/~ID~/info.0.json}
    web-url: ${TOON_XKCD_WEB_URL:https://xkcd.com/~ID~/}
    # see PDL for additional pull comments
    pull-delay-ms: ${TOON_XKCD_PULL_DELAY_MS:150} # (pulling XKCD JSON is slower, so delay larger)
    pull-delay-min: ${TOON_XKCD_PULL_DELAY_MIN:60}
logging:
  level:
    root: WARN
    com.mrazjava.toonfeed: INFO
    # switch to DEBUG to snoop on execution dates
    com.mrazjava.toonfeed.AbstractToonfeedTrigger: INFO
    # switch to DEBUG to monitor XKCD action
    com.mrazjava.toonfeed.xkcd.XkcdMessageSource: INFO
    sun.net.www.protocol.http.HttpURLConnection: INFO
